"""followers

Revision ID: 772caf5fc72b
Revises: 43531e170424
Create Date: 2018-03-04 21:14:39.918143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772caf5fc72b'
down_revision = '43531e170424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
